### ISSUE TITLE
Use org.freedesktop.FileManager1 instead of xdg-open to open folders in filemanager

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.georgefb.quickaccess#3]
It was added in https://github.com/flathub/com.georgefb.quickaccess/commit/fdc74df4254fc105ff3a3c8f6ab1dd2cfc7981b1 without any explanation

**Comment by g-fb** [comment]
> flatpak-spawn
> --host
> Run the command unsandboxed on the host. This requires access to the org.freedesktop.Flatpak D-Bus interface

https://docs.flatpak.org/en/latest/flatpak-command-reference.html

**Comment by bbhtt** [comment]
> > flatpak-spawn
> > --host
> > Run the command unsandboxed on the host. This requires access to the org.freedesktop.Flatpak D-Bus interface
> 
> https://docs.flatpak.org/en/latest/flatpak-command-reference.html

I know that, question is why do you need it?

**Comment by g-fb** [comment]
So i can open system folders.

**Comment by bbhtt** [comment]
In the filemanager? Why not use the `org.freedesktop.Filemanager1` interface?

**Comment by g-fb** [comment]
Feel free to submit a PR.

**Comment by bbhtt** [comment]
> Feel free to submit a PR.

I won't have time sorry but this should not be difficult.

You should never use flatpak-spawn because it allows the application to execute arbitrary commands from the sandbox making it useless.

Let's keep it open, since this seems to be something that can be solved if anyone else wants to.
